FROM python:3.7-slim
WORKDIR /app
COPY requirements.txt /app
RUN pip3 install -r /app/requirements.txt --no-cache-dir
COPY . ..yamdb_final/ /app
CMD ["gunicorn", "yamdb_final.wsgi:application", "--bind", "0:8000" ]
